#################
### AUTOSTART ###
#################

exec-once = waybar & swaync & hypridle
exec-once = gtk-launch Whatsapp
exec-once = gtk-launch com.discordapp.Discord
exec-once = hyprctl dispatch exec [workspace 2 silent] -- launch-browser
exec-once = hyprctl dispatch exec [workspace 1] -- wezterm

exec-once = playerctld daemon
