#################
### AUTOSTART ###
#################

exec-once = waybar & swaync & hypridle
exec-once = launch-or-focus-webapp "whatsapp" "https://web.whatsapp.com"
exec-once = launch-or-focus-webapp "discord" "https://discord.com/channels/@me"
# Use sleep to ensure the apps are launched on the correct workspace
exec-once = sleep 1 && hyprctl dispatch workspace 2 && launch-browser
exec-once = sleep 2 && hyprctl dispatch workspace 1 && $terminal

exec-once = playerctld daemon
