#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = ADW_DISABLE_PORTAL,1

# Cedilla support (' + c = ç)
# Also requires editing /usr/share/X11/locale/en_US.UTF-8/Compose
# See FIX_CEDILLA.md for details
env = XCOMPOSEFILE,$HOME/.XCompose
env = XMODIFIERS,@im=xim
env = GTK_IM_MODULE,cedilla
env = QT_IM_MODULE,cedilla
