#####################
### WINDOW RULES  ###
#####################

# Global rules
windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Web apps — workspace 3 (Social)
windowrule {
    name = force-tile-whatsapp
    match:title = .*[Ww]hats[Aa]pp.*

    tile = true
    workspace = 3
}

windowrule {
    name = force-tile-discord
    match:class = .*chrome-discord.*

    tile = true
    workspace = 3
}

# Workspace 4 (Media/Entertainment)
windowrule {
    name = force-tile-youtube-music
    match:class = ^(Google-chrome)$ 
    match:title = .*music\.youtube\.com.* 

    tile = true
    workspace = 4
}

windowrule {
    name = steam
    match:class = ^(steam)$

    tile = false
    workspace = 4
}

# Workspace 5 (Games)
windowrule {
    name = counter-strike-window
    match:class = cs2

    workspace = 5
}

windowrule {
    name = age-of-empires-window
    match:title = .*Age of Empires III.*

    workspace = 5
}

windowrule {
    name = dota-2-window
    match:class = dota2

    workspace = 5
}


windowrule {
    name = claude
    match:class = ^(Google-chrome)$ 
    match:title = .*claude.*

    tile = true
    workspace = 3
}

#####################
### LAYER RULES   ###
#####################

layerrule = blur off, match:namespace waybar

layerrule {
    name = rofi
    match:class = rofi
    blur = true
}
