import QtQuick
import Qt5Compat.GraphicalEffects
import SddmComponents 2.0

Rectangle {
    id: root
    width: Screen.width || 1920
    height: Screen.height || 1080

    // Material You colors (generated by matugen)
    readonly property color bgColor: "{{colors.surface.default.hex}}"
    readonly property color surfaceContainer: "{{colors.surface_container.default.hex}}"
    readonly property color surfaceContainerHigh: "{{colors.surface_container_high.default.hex}}"
    readonly property color surfaceDim: "{{colors.surface_dim.default.hex}}"
    readonly property color primaryColor: "{{colors.primary.default.hex}}"
    readonly property color onSurface: "{{colors.on_surface.default.hex}}"
    readonly property color onSurfaceVariant: "{{colors.on_surface_variant.default.hex}}"
    readonly property color outlineVariant: "{{colors.outline_variant.default.hex}}"
    readonly property color errorColor: "{{colors.error.default.hex}}"

    color: bgColor

    property string currentUser: userModel.lastUser || "User"
    property int sessionIndex: {
        for (var i = 0; i < sessionModel.rowCount(); i++) {
            var name = (sessionModel.data(sessionModel.index(i, 0), Qt.DisplayRole) || "").toString()
            if (name.indexOf("uwsm") !== -1 || name.indexOf("hyprland") !== -1 || name.indexOf("Hyprland") !== -1)
                return i
        }
        return sessionModel.lastIndex
    }

    Connections {
        target: sddm
        function onLoginFailed() {
            errorMessage.text = "Authentication failed"
            password.text = ""
            password.focus = true
        }
        function onLoginSucceeded() {
            errorMessage.text = ""
        }
    }

    // Background wallpaper (hidden — used as blur source)
    Image {
        id: backgroundImage
        anchors.fill: parent
        source: "background.jpg"
        fillMode: Image.PreserveAspectCrop
        visible: false
    }

    // Full-screen blurred background
    FastBlur {
        anchors.fill: parent
        source: backgroundImage
        radius: 32
        visible: backgroundImage.status === Image.Ready
    }

    // Light scrim over blurred background
    Rectangle {
        anchors.fill: parent
        color: "#000000"
        opacity: backgroundImage.status === Image.Ready ? 0.25 : 0
    }

    // ── LEFT SIDE: Clock & Date ──
    Item {
        id: leftPanel
        anchors.left: parent.left
        anchors.top: parent.top
        anchors.bottom: parent.bottom
        width: parent.width * 0.55

        Column {
            anchors.centerIn: parent
            spacing: root.height * 0.01

            // Time
            Text {
                id: clock
                text: Qt.formatTime(new Date(), "hh:mm")
                color: root.primaryColor
                font.family: "Noto Sans"
                font.weight: Font.Bold
                font.pixelSize: root.height * 0.18

                layer.enabled: true
                layer.effect: DropShadow {
                    horizontalOffset: 0; verticalOffset: 2
                    radius: 12; samples: 25; color: "#80000000"
                }

                Timer {
                    interval: 30000
                    running: true
                    repeat: true
                    onTriggered: clock.text = Qt.formatTime(new Date(), "hh:mm")
                }
            }

            // Day of week
            Text {
                id: dayLabel
                text: Qt.formatDate(new Date(), "dddd")
                color: root.onSurface
                font.family: "Noto Sans"
                font.weight: Font.Medium
                font.pixelSize: root.height * 0.035

                layer.enabled: true
                layer.effect: DropShadow {
                    horizontalOffset: 0; verticalOffset: 1
                    radius: 8; samples: 17; color: "#80000000"
                }

                Timer {
                    interval: 60000
                    running: true
                    repeat: true
                    onTriggered: dayLabel.text = Qt.formatDate(new Date(), "dddd")
                }
            }

            // Date
            Text {
                id: dateLabel
                text: Qt.formatDate(new Date(), "MMMM d, yyyy")
                color: root.onSurfaceVariant
                font.family: "Noto Sans"
                font.weight: Font.Normal
                font.pixelSize: root.height * 0.025

                layer.enabled: true
                layer.effect: DropShadow {
                    horizontalOffset: 0; verticalOffset: 1
                    radius: 6; samples: 13; color: "#60000000"
                }

                Timer {
                    interval: 60000
                    running: true
                    repeat: true
                    onTriggered: dateLabel.text = Qt.formatDate(new Date(), "MMMM d, yyyy")
                }
            }
        }
    }

    // ── RIGHT SIDE: Login panel ──
    Item {
        id: rightPanel
        anchors.left: leftPanel.right
        anchors.right: parent.right
        anchors.top: parent.top
        anchors.bottom: parent.bottom

        Column {
            anchors.centerIn: parent
            spacing: root.height * 0.02
            width: parent.width * 0.7

            // User avatar
            Item {
                width: avatarSize
                height: avatarSize
                anchors.horizontalCenter: parent.horizontalCenter

                readonly property real avatarSize: root.height * 0.11

                Rectangle {
                    id: avatarMask
                    anchors.fill: parent
                    radius: width / 2
                    color: root.surfaceContainerHigh
                    clip: true

                    Image {
                        id: avatarImage
                        anchors.fill: parent
                        source: "file:///usr/share/sddm/faces/" + root.currentUser + ".face.icon"
                        fillMode: Image.PreserveAspectCrop
                        visible: status === Image.Ready
                    }

                    // Fallback: first letter
                    Text {
                        anchors.centerIn: parent
                        text: root.currentUser.charAt(0).toUpperCase()
                        color: root.primaryColor
                        font.family: "Noto Sans"
                        font.weight: Font.Medium
                        font.pixelSize: parent.height * 0.45
                        visible: avatarImage.status !== Image.Ready
                    }
                }

                // Avatar ring
                Rectangle {
                    anchors.fill: parent
                    radius: width / 2
                    color: "transparent"
                    border.color: root.primaryColor
                    border.width: 2
                }
            }

            // Username
            Text {
                text: root.currentUser
                color: root.onSurface
                font.family: "Noto Sans"
                font.weight: Font.Medium
                font.pixelSize: root.height * 0.028
                anchors.horizontalCenter: parent.horizontalCenter
            }

            // Spacer
            Item { width: 1; height: root.height * 0.015 }

            // Password field
            Rectangle {
                id: inputContainer
                width: Math.min(parent.width, 320)
                height: root.height * 0.055
                radius: height / 2
                color: Qt.rgba(root.surfaceContainer.r,
                               root.surfaceContainer.g,
                               root.surfaceContainer.b, 0.7)
                border.color: password.activeFocus ? root.primaryColor : root.outlineVariant
                border.width: password.activeFocus ? 2 : 1
                anchors.horizontalCenter: parent.horizontalCenter

                TextInput {
                    id: password
                    anchors.fill: parent
                    anchors.leftMargin: inputContainer.height * 0.45
                    anchors.rightMargin: inputContainer.height * 0.45
                    verticalAlignment: TextInput.AlignVCenter
                    echoMode: TextInput.Password
                    font.family: "Noto Sans"
                    font.pixelSize: root.height * 0.018
                    font.letterSpacing: 2
                    passwordCharacter: "\u2022"
                    color: root.onSurface
                    focus: true

                    Keys.onPressed: {
                        if (event.key === Qt.Key_Return || event.key === Qt.Key_Enter) {
                            sddm.login(root.currentUser, password.text, root.sessionIndex)
                            event.accepted = true
                        }
                    }

                    // Placeholder
                    Text {
                        text: "Password"
                        color: root.onSurfaceVariant
                        font.family: password.font.family
                        font.pixelSize: password.font.pixelSize
                        font.italic: true
                        anchors.verticalCenter: parent.verticalCenter
                        visible: password.text.length === 0 && !password.activeFocus
                    }
                }
            }

            // Error message
            Text {
                id: errorMessage
                text: ""
                color: root.errorColor
                font.family: "Noto Sans"
                font.pixelSize: root.height * 0.016
                anchors.horizontalCenter: parent.horizontalCenter
            }
        }
    }

    Component.onCompleted: password.forceActiveFocus()
}
