[colors]
background = "#15130c"
foreground = "#e8e2d4"
cursor_bg = "#e8e2d4"
cursor_border = "#e8e2d4"
cursor_fg = "#ccc6b4"
selection_bg = "#d0c7a2"
selection_fg = "#363016"

split = "#d0c7a2"

ansi = [
    "#191919",
    "#D90202",
    "#7FB11B",
    "#FFD739",
    "#3570D7",
    "#BE84FF",
    "#66D9EF",
    "#F8F8F8"
]

brights = [
    "#4D4D4D",
    "#FF4747",
    "#A0D04D",
    "#FFEB4D",
    "#6A9FF7",
    "#D9A6FF",
    "#80F5FF",
    "#FFFFFF"
]
