[colors]
background = "#101418"
foreground = "#e0e2e8"
cursor_bg = "#e0e2e8"
cursor_border = "#e0e2e8"
cursor_fg = "#c2c7ce"
selection_bg = "#b8c8d9"
selection_fg = "#23323f"

split = "#b8c8d9"

ansi = [
    "#191919",
    "#D90202",
    "#7FB11B",
    "#FFD739",
    "#3570D7",
    "#BE84FF",
    "#66D9EF",
    "#F8F8F8"
]

brights = [
    "#4D4D4D",
    "#FF4747",
    "#A0D04D",
    "#FFEB4D",
    "#6A9FF7",
    "#D9A6FF",
    "#80F5FF",
    "#FFFFFF"
]
